# Generated by Django 6.0.6 on 2026-07-23 16:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='companies.company')),
            ],
            options={
                'db_table': 'candidates',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company'], name='candidates_company_a55a1a_idx'), models.Index(fields=['email'], name='candidates_email_32f680_idx'), models.Index(fields=['first_name'], name='candidates_first_n_48ff57_idx'), models.Index(fields=['last_name'], name='candidates_last_na_667fb4_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'email'), name='unique_candidate_email_per_company')],
            },
        ),
    ]
