# Generated by Django 6.0.6 on 2026-08-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='public_token',
            field=models.CharField(default='asdadsasd', editable=False, max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
