# Generated by Django 6.0.6 on 2026-08-07 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_public_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='public_token',
            new_name='apply_token',
        ),
    ]
