# Generated by Django 6.0.6 on 2026-07-29 08:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume', models.FileField(upload_to='applications/resumes/')),
                ('cover_letter', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('screening', 'Screening'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview'), ('offered', 'Offered'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='applied', max_length=20)),
                ('source', models.CharField(choices=[('career_portal', 'Career Portal'), ('referral', 'Referral'), ('linkedin', 'LinkedIn'), ('indeed', 'Indeed'), ('manual', 'Manual')], default='career_portal', max_length=20)),
                ('ai_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('resume_text', models.TextField(blank=True)),
                ('parsed_data', models.JSONField(blank=True, default=dict)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='candidates.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'applications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['job'], name='application_job_id_c2a30a_idx'), models.Index(fields=['candidate'], name='application_candida_0452de_idx'), models.Index(fields=['status'], name='application_status_e61111_idx'), models.Index(fields=['ai_score'], name='application_ai_scor_5e1a74_idx')],
                'constraints': [models.UniqueConstraint(fields=('candidate', 'job'), name='unique_candidate_job_application')],
            },
        ),
    ]
